opt_type: "wan2.1_t2v_1.3b_dmd"

optimizer:
  name: "adamw"
  lr: 0.000002
  betas:
    - 0.
    - 0.999
  weight_decay: 0.01

lr_scheduler:
  name: "constant"

train:
  batch_size_per_gpu: 1
  gradient_accumulation_steps: 1
  sharding_strategy: "hybrid_full"
  wrap_strategy: "transformer"
  epochs: 10
  log_freq: 1
  early_eval_freq: 20
  early_eval: 200
  eval_freq: 100
  save_freq: 500
  eval_freq_epoch: 5
  save_freq_epoch: 10
  use_ema: true
  ema_weight: 0.99
  ema_start_step: 200

val:
  batch_size_per_gpu: 1
